name: CI Pipeline

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup project
        run: make setup

      - name: Run tests
        run: make test

      - name: Run linter
        run: make lint